// <auto-generated />
using System;
using Fidelity.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fidelity.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251225150324_AddClientePassword")]
    partial class AddClientePassword
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fidelity.Shared.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("CodiceFidelity")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataRegistrazione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PrivacyAccettata")
                        .HasColumnType("bit");

                    b.Property<int>("PuntiTotali")
                        .HasColumnType("int");

                    b.Property<int>("PuntoVenditaRegistrazioneId")
                        .HasColumnType("int");

                    b.Property<int>("ResponsabileRegistrazioneId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CodiceFidelity")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PuntoVenditaRegistrazioneId");

                    b.HasIndex("ResponsabileRegistrazioneId");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("Fidelity.Shared.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataScadenza")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoSconto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ValoreSconto")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("Fidelity.Shared.Models.CouponAssegnato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("CouponId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAssegnazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUtilizzo")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Utilizzato")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("CouponId");

                    b.ToTable("CouponAssegnati");
                });

            modelBuilder.Entity("Fidelity.Shared.Models.PuntoVendita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("Citta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Indirizzo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.ToTable("PuntiVendita");
                });

            modelBuilder.Entity("Fidelity.Shared.Models.Responsabile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RichiestaResetPassword")
                        .HasColumnType("bit");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UltimoAccesso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Responsabili");
                });

            modelBuilder.Entity("Fidelity.Shared.Models.ResponsabilePuntoVendita", b =>
                {
                    b.Property<int>("ResponsabileId")
                        .HasColumnType("int");

                    b.Property<int>("PuntoVenditaId")
                        .HasColumnType("int");

                    b.HasKey("ResponsabileId", "PuntoVenditaId");

                    b.HasIndex("PuntoVenditaId");

                    b.ToTable("ResponsabilePuntiVendita");
                });

            modelBuilder.Entity("Fidelity.Shared.Models.TokenRegistrazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataScadenza")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUtilizzo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PuntoVenditaId")
                        .HasColumnType("int");

                    b.Property<int>("ResponsabileId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("Utilizzato")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PuntoVenditaId");

                    b.HasIndex("ResponsabileId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("TokenRegistrazione");
                });

            modelBuilder.Entity("Fidelity.Shared.Models.Transazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataTransazione")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ImportoSpesa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PuntiAssegnati")
                        .HasColumnType("int");

                    b.Property<int>("PuntoVenditaId")
                        .HasColumnType("int");

                    b.Property<int>("ResponsabileId")
                        .HasColumnType("int");

                    b.Property<string>("TipoTransazione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PuntoVenditaId");

                    b.HasIndex("ResponsabileId");

                    b.ToTable("Transazioni");
                });

            modelBuilder.Entity("Fidelity.Shared.Models.Cliente", b =>
                {
                    b.HasOne("Fidelity.Shared.Models.PuntoVendita", "PuntoVenditaRegistrazione")
                        .WithMany("ClientiRegistrati")
                        .HasForeignKey("PuntoVenditaRegistrazioneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fidelity.Shared.Models.Responsabile", "ResponsabileRegistrazione")
                        .WithMany()
                        .HasForeignKey("ResponsabileRegistrazioneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PuntoVenditaRegistrazione");

                    b.Navigation("ResponsabileRegistrazione");
                });

            modelBuilder.Entity("Fidelity.Shared.Models.CouponAssegnato", b =>
                {
                    b.HasOne("Fidelity.Shared.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fidelity.Shared.Models.Coupon", "Coupon")
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Coupon");
                });

            modelBuilder.Entity("Fidelity.Shared.Models.ResponsabilePuntoVendita", b =>
                {
                    b.HasOne("Fidelity.Shared.Models.PuntoVendita", "PuntoVendita")
                        .WithMany("ResponsabilePuntiVendita")
                        .HasForeignKey("PuntoVenditaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fidelity.Shared.Models.Responsabile", "Responsabile")
                        .WithMany("ResponsabilePuntiVendita")
                        .HasForeignKey("ResponsabileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PuntoVendita");

                    b.Navigation("Responsabile");
                });

            modelBuilder.Entity("Fidelity.Shared.Models.TokenRegistrazione", b =>
                {
                    b.HasOne("Fidelity.Shared.Models.PuntoVendita", "PuntoVendita")
                        .WithMany()
                        .HasForeignKey("PuntoVenditaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fidelity.Shared.Models.Responsabile", "Responsabile")
                        .WithMany()
                        .HasForeignKey("ResponsabileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PuntoVendita");

                    b.Navigation("Responsabile");
                });

            modelBuilder.Entity("Fidelity.Shared.Models.Transazione", b =>
                {
                    b.HasOne("Fidelity.Shared.Models.Cliente", "Cliente")
                        .WithMany("Transazioni")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fidelity.Shared.Models.PuntoVendita", "PuntoVendita")
                        .WithMany("Transazioni")
                        .HasForeignKey("PuntoVenditaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fidelity.Shared.Models.Responsabile", "Responsabile")
                        .WithMany()
                        .HasForeignKey("ResponsabileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("PuntoVendita");

                    b.Navigation("Responsabile");
                });

            modelBuilder.Entity("Fidelity.Shared.Models.Cliente", b =>
                {
                    b.Navigation("Transazioni");
                });

            modelBuilder.Entity("Fidelity.Shared.Models.PuntoVendita", b =>
                {
                    b.Navigation("ClientiRegistrati");

                    b.Navigation("ResponsabilePuntiVendita");

                    b.Navigation("Transazioni");
                });

            modelBuilder.Entity("Fidelity.Shared.Models.Responsabile", b =>
                {
                    b.Navigation("ResponsabilePuntiVendita");
                });
#pragma warning restore 612, 618
        }
    }
}
