// <auto-generated />
using System;
using Fidelity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fidelity.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fidelity.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AccountLockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("CodiceFidelity")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataRegistrazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Livello")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Bronze");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PrivacyAccettata")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PrivacyAccettataData")
                        .HasColumnType("datetime2");

                    b.Property<int>("PuntiSpesi")
                        .HasColumnType("int");

                    b.Property<int>("PuntiTotali")
                        .HasColumnType("int");

                    b.Property<int?>("PuntoVenditaRegistrazioneId")
                        .HasColumnType("int");

                    b.Property<int?>("ResponsabileRegistrazioneId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CodiceFidelity")
                        .IsUnique();

                    b.HasIndex("Cognome");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Nome");

                    b.HasIndex("PuntoVenditaRegistrazioneId");

                    b.HasIndex("ResponsabileRegistrazioneId");

                    b.HasIndex("Attivo", "IsDeleted");

                    b.ToTable("Clienti", (string)null);
                });

            modelBuilder.Entity("Fidelity.Domain.Entities.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AssegnazioneAutomatica")
                        .HasColumnType("bit");

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataScadenza")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("ImportoMinimoOrdine")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsCouponBenvenuto")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LimiteUtilizzoGlobale")
                        .HasColumnType("int");

                    b.Property<int?>("LimiteUtilizzoPerCliente")
                        .HasColumnType("int");

                    b.Property<string>("LivelloMinimoRichiesto")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PuntiRichiesti")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TipoSconto")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Percentuale");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilizziTotali")
                        .HasColumnType("int");

                    b.Property<decimal>("ValoreSconto")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.HasIndex("DataScadenza");

                    b.HasIndex("Attivo", "IsDeleted");

                    b.ToTable("Coupons", (string)null);
                });

            modelBuilder.Entity("Fidelity.Domain.Entities.CouponAssegnato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssegnatoDa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("CouponId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAssegnazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUtilizzo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Manuale");

                    b.Property<int?>("PuntoVenditaUtilizzoId")
                        .HasColumnType("int");

                    b.Property<int?>("ResponsabileUtilizzoId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("TransazioneUtilizzoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Utilizzato")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PuntoVenditaUtilizzoId");

                    b.HasIndex("ResponsabileUtilizzoId");

                    b.HasIndex("ClienteId", "Utilizzato");

                    b.HasIndex("CouponId", "ClienteId");

                    b.ToTable("CouponAssegnati", (string)null);
                });

            modelBuilder.Entity("Fidelity.Domain.Entities.PuntoVendita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("CAP")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Citta")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Indirizzo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OrariApertura")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PuntiPerEuro")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0.1m);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.ToTable("PuntiVendita", (string)null);
                });

            modelBuilder.Entity("Fidelity.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ResponsabileId")
                        .HasColumnType("int");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime?>("RevokedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ExpiryDate");

                    b.HasIndex("ResponsabileId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Fidelity.Domain.Entities.Responsabile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AccountLockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NomeCompleto")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("RichiestaResetPassword")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Responsabile");

                    b.Property<DateTime?>("UltimoAccesso")
                        .HasColumnType("datetime2");

                    b.Property<string>("UltimoAccessoIP")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Responsabili", (string)null);
                });

            modelBuilder.Entity("Fidelity.Domain.Entities.ResponsabilePuntoVendita", b =>
                {
                    b.Property<int>("ResponsabileId")
                        .HasColumnType("int");

                    b.Property<int>("PuntoVenditaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAssociazione")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Principale")
                        .HasColumnType("bit");

                    b.HasKey("ResponsabileId", "PuntoVenditaId");

                    b.HasIndex("PuntoVenditaId");

                    b.ToTable("ResponsabilePuntiVendita", (string)null);
                });

            modelBuilder.Entity("Fidelity.Domain.Entities.TokenRegistrazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataScadenza")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUtilizzo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PuntoVenditaId")
                        .HasColumnType("int");

                    b.Property<int>("ResponsabileId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Utilizzato")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("PuntoVenditaId");

                    b.HasIndex("ResponsabileId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("Email", "Utilizzato");

                    b.ToTable("TokenRegistrazione", (string)null);
                });

            modelBuilder.Entity("Fidelity.Domain.Entities.Transazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("CouponAssegnatoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataTransazione")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ImportoSpesa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PuntiAssegnati")
                        .HasColumnType("int");

                    b.Property<int>("PuntoVenditaId")
                        .HasColumnType("int");

                    b.Property<int?>("ResponsabileId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Accumulo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CouponAssegnatoId")
                        .IsUnique()
                        .HasFilter("[CouponAssegnatoId] IS NOT NULL");

                    b.HasIndex("DataTransazione");

                    b.HasIndex("PuntoVenditaId");

                    b.HasIndex("ResponsabileId");

                    b.HasIndex("ClienteId", "DataTransazione");

                    b.ToTable("Transazioni", (string)null);
                });

            modelBuilder.Entity("Fidelity.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("Fidelity.Domain.Entities.PuntoVendita", "PuntoVenditaRegistrazione")
                        .WithMany("ClientiRegistrati")
                        .HasForeignKey("PuntoVenditaRegistrazioneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fidelity.Domain.Entities.Responsabile", "ResponsabileRegistrazione")
                        .WithMany()
                        .HasForeignKey("ResponsabileRegistrazioneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PuntoVenditaRegistrazione");

                    b.Navigation("ResponsabileRegistrazione");
                });

            modelBuilder.Entity("Fidelity.Domain.Entities.CouponAssegnato", b =>
                {
                    b.HasOne("Fidelity.Domain.Entities.Cliente", "Cliente")
                        .WithMany("CouponAssegnati")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fidelity.Domain.Entities.Coupon", "Coupon")
                        .WithMany("CouponAssegnati")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fidelity.Domain.Entities.PuntoVendita", "PuntoVenditaUtilizzo")
                        .WithMany()
                        .HasForeignKey("PuntoVenditaUtilizzoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fidelity.Domain.Entities.Responsabile", "ResponsabileUtilizzo")
                        .WithMany()
                        .HasForeignKey("ResponsabileUtilizzoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("Coupon");

                    b.Navigation("PuntoVenditaUtilizzo");

                    b.Navigation("ResponsabileUtilizzo");
                });

            modelBuilder.Entity("Fidelity.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Fidelity.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fidelity.Domain.Entities.Responsabile", "Responsabile")
                        .WithMany()
                        .HasForeignKey("ResponsabileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Cliente");

                    b.Navigation("Responsabile");
                });

            modelBuilder.Entity("Fidelity.Domain.Entities.ResponsabilePuntoVendita", b =>
                {
                    b.HasOne("Fidelity.Domain.Entities.PuntoVendita", "PuntoVendita")
                        .WithMany("ResponsabilePuntiVendita")
                        .HasForeignKey("PuntoVenditaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fidelity.Domain.Entities.Responsabile", "Responsabile")
                        .WithMany("ResponsabilePuntiVendita")
                        .HasForeignKey("ResponsabileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PuntoVendita");

                    b.Navigation("Responsabile");
                });

            modelBuilder.Entity("Fidelity.Domain.Entities.TokenRegistrazione", b =>
                {
                    b.HasOne("Fidelity.Domain.Entities.PuntoVendita", "PuntoVendita")
                        .WithMany()
                        .HasForeignKey("PuntoVenditaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fidelity.Domain.Entities.Responsabile", "Responsabile")
                        .WithMany("TokenRegistrazioniCreati")
                        .HasForeignKey("ResponsabileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PuntoVendita");

                    b.Navigation("Responsabile");
                });

            modelBuilder.Entity("Fidelity.Domain.Entities.Transazione", b =>
                {
                    b.HasOne("Fidelity.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Transazioni")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fidelity.Domain.Entities.CouponAssegnato", "CouponAssegnato")
                        .WithOne("TransazioneUtilizzo")
                        .HasForeignKey("Fidelity.Domain.Entities.Transazione", "CouponAssegnatoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fidelity.Domain.Entities.PuntoVendita", "PuntoVendita")
                        .WithMany("Transazioni")
                        .HasForeignKey("PuntoVenditaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fidelity.Domain.Entities.Responsabile", "Responsabile")
                        .WithMany("Transazioni")
                        .HasForeignKey("ResponsabileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("CouponAssegnato");

                    b.Navigation("PuntoVendita");

                    b.Navigation("Responsabile");
                });

            modelBuilder.Entity("Fidelity.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("CouponAssegnati");

                    b.Navigation("Transazioni");
                });

            modelBuilder.Entity("Fidelity.Domain.Entities.Coupon", b =>
                {
                    b.Navigation("CouponAssegnati");
                });

            modelBuilder.Entity("Fidelity.Domain.Entities.CouponAssegnato", b =>
                {
                    b.Navigation("TransazioneUtilizzo");
                });

            modelBuilder.Entity("Fidelity.Domain.Entities.PuntoVendita", b =>
                {
                    b.Navigation("ClientiRegistrati");

                    b.Navigation("ResponsabilePuntiVendita");

                    b.Navigation("Transazioni");
                });

            modelBuilder.Entity("Fidelity.Domain.Entities.Responsabile", b =>
                {
                    b.Navigation("ResponsabilePuntiVendita");

                    b.Navigation("TokenRegistrazioniCreati");

                    b.Navigation("Transazioni");
                });
#pragma warning restore 612, 618
        }
    }
}
